### ISSUE TITLE
Owner of the fork repository

### ISSUE THREAD

**Issue by acpaulo** [tmichoel/causal-inference-short-course#1]
Hi Tom,

I tried to fork your repository today, but I'm having some trouble with the owner settings. When I attempt to change the owner, it only shows my name and doesn't give me the option to select anyone else. Should the owner be set to 'tmichoel'? It doesn't even appear in the dropdown menu.

I haven't made any other changes because I'm unsure if I've done something wrong.

Thanks a lot and sorry for the inconvenience.

Best regards,
Cristina

**Comment by tmichoel** [comment]
Hi Cristine,

Sorry for the late reply. You don't have to change anything to the owner settings, just keep yourself as the owner of your fork and things should work.

Best,
Tom
